Finished hw 20 (MVC, thymeleaf, listener, interceptors)
Sofasmile/SpringMVC pull request #1
Opened 2019-05-16 05:52 UTC by Sofasmile

2019-05-18 06:53 UTC, Anderwerty requested changes

2019-05-18 06:53 UTC, Anderwerty commented on src/main/java/net/spring/bpp/StudentBeanPostProcessor.java
> +    private final Logger LOGGER = LoggerFactory.getLogger(this.getClass());
Modifier static is miss.

2019-05-18 06:53 UTC, Anderwerty commented on src/main/java/net/spring/config/WebConfiguration.java
> +    StudentInterceptor studentInterceptor;
What about encapsulation?

2019-05-18 06:53 UTC, Anderwerty commented on src/main/java/net/spring/config/WebConfiguration.java
> +    @Autowired
It is better to use a constructor for dependency injection.
https://www.vojtechruzicka.com/field-dependency-injection-considered-harmful/

2019-05-18 06:53 UTC, Anderwerty commented on src/main/java/net/spring/controller/AppController.java
> +    @Autowired
The same

2019-05-18 06:53 UTC, Anderwerty commented on src/main/java/net/spring/controller/AppController.java
> +    @RequestMapping("/")
Please look at  annotations 
@GetMapping
@PostMapping
@PutMapping
@DeleteMapping
@PatchMapping
and use them
https://www.baeldung.com/spring-requestmapping

2019-05-18 06:53 UTC, Anderwerty commented on src/main/java/net/spring/controller/AppController.java
> +    @RequestMapping("/delete/{id}")
Why http method is GET not DELETE?

2019-05-18 06:53 UTC, Anderwerty commented on src/main/java/net/spring/interceptor/StudentInterceptor.java
> +    private final Logger LOGGER = LoggerFactory.getLogger(this.getClass());
Modifier static is missed.

2019-05-18 06:53 UTC, Anderwerty commented on src/main/java/net/spring/service/StudentServiceImpl.java
> +    private StudentRepository repository;
The same

2019-05-18 06:53 UTC, Anderwerty commented on src/main/java/net/spring/service/StudentServiceImpl.java
> +        return repository.findById(id).get();
It is possible to get an Exception here. Please fix it.

2019-05-19 09:36 UTC, Sofasmile commented on src/main/java/net/spring/controller/AppController.java
> +    @RequestMapping("/delete/{id}")
Because I try to delete by id

2019-05-20 18:55 UTC, Anderwerty requested changes

2019-05-20 18:55 UTC, Anderwerty commented on src/main/java/net/spring/controller/AppController.java
> +    @DeleteMapping("/delete")
Where do you get @RequestParam?

2019-05-20 18:55 UTC, Anderwerty commented on src/main/java/net/spring/controller/AppController.java
> +    public ModelAndView editStudentForm(@Valid @RequestParam Long id) {
Where do you get @RequestParam?

2019-05-20 18:55 UTC, Anderwerty commented on src/main/java/net/spring/entity/CreatableEntity.java
> +    private Long createdDate;
Why not LocalDate? Please use it.

2019-05-20 18:55 UTC, Anderwerty commented on src/main/java/net/spring/config/WebConfiguration.java
> +    @Autowired
As you use Lombok, please use Lombok annotation for a constructor.
https://www.baeldung.com/spring-injection-lombok
Example: @RequiredArgsConstructor(onConstructor = @__(@Autowired))

2019-05-20 18:55 UTC, Anderwerty commented on src/main/java/net/spring/controller/AppController.java
> +    @Autowired
As you use Lombok, please use Lombok annotation for a constructor.
https://www.baeldung.com/spring-injection-lombok
Example: @RequiredArgsConstructor(onConstructor = @__(@Autowired))

2019-05-20 18:55 UTC, Anderwerty commented on src/main/java/net/spring/listener/StudentCreatableListener.java
> +        entity.setCreatedDate(new Date().getTime());
Why not use LocalDate.now()?

2019-05-20 18:55 UTC, Anderwerty commented on src/main/java/net/spring/service/StudentServiceImpl.java
> +    public StudentServiceImpl(StudentRepository repository) {
Please use Lombok

2019-05-21 09:13 UTC, Anderwerty approved these changes

2019-05-23 10:21 UTC, merged