Security with autorisation and autentication
Sofasmile/SpringMVC pull request #2
Opened 2019-05-23 14:16 UTC by Sofasmile

2019-05-24 11:15 UTC, Taniann requested changes
good but please make a little fixing

2019-05-24 11:15 UTC, Taniann commented on src/main/java/net/spring/service/RoleService.java
> +
remove redundant blank line

2019-05-24 11:15 UTC, Taniann commented on src/main/java/net/spring/service/UserService.java
> +    User findByUserName(String userName);
better name findByUserName -> findByName

you already have word "User" in service name

2019-05-24 11:15 UTC, Taniann commented on src/main/java/net/spring/service/UserService.java
> +    void saveUser(User user);
the same saveUser -> save

2019-05-24 11:15 UTC, Taniann commented on src/main/java/net/spring/service/UserServiceImpl.java
> +        return userRepository.findByUserName(userName).orElse(null);
or else better throw custom exception with message for example "User with this username not found"

2019-05-25 07:35 UTC, Aleksandr04 commented on src/main/java/net/spring/controller/LoginController.java
> +    public ModelAndView createNewUser(User user, BindingResult bindingResult) {
Please add NotNull annotation

2019-05-25 07:35 UTC, Aleksandr04 commented on src/main/java/net/spring/controller/AppController.java
> +    @PostMapping("/students/save")
Please remove "students" from this and add it to @RequestMapping

2019-05-25 07:37 UTC, Aleksandr04 commented on src/main/java/net/spring/entity/user/User.java
> +    private int active;
change on boolean

2019-05-27 09:57 UTC, Taniann approved these changes
good

2019-05-27 19:00 UTC, merged